---
- name: Deploy OpenFaaS Helm Chart
  kubernetes.core.helm:
    name: openfaas
    chart_ref: "{{ role_path }}/files/openfaas"
    values:
      gateway:
        image: "{{ openfaas_gateway_image }}"
      faasnetes:
        image: "{{ openfaas_netes_image }}"
      offload:
        enabled: "{{ offload_enabled }}"
        hostalias: "{{ hostalias }}"
      p2p:
        ip: "{{ ansible_host }}"
      ingress:
        hosts:
        - host: "{{ hostname }}"
          serviceName: gateway
          servicePort: 8080
          path: /
        ingressClassName: "{{ ingressClassName }}"
    release_namespace: openfaas
    create_namespace: true
    wait: True
    timeout: 600s
    kubeconfig: "openfaas/kubeconfig/{{ inventory_hostname }}-kubeconfig"
  delegate_to: localhost
  tags: openfaas_helm_update