---
- name: Copy cluster's kubeconfig file to Helm Chart
  copy:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/openfaas/kubeconfig/"
  with_fileglob:
    - "*-kubeconfig"
  delegate_to: localhost

- name: Deploy OpenFaaS Helm Chart
  kubernetes.core.helm:
    name: openfaas
    chart_ref: "{{ role_path }}/files/openfaas"
    values:
      gateway:
        image: "{{ openfaas_gateway_image }}"
      faasnetes:
        image: "{{ openfaas_netes_image }}"
      offload:
        enabled: "{{ offload_enabled }}"
        hostalias: "{{ hostalias }}"
      ingress:
        hosts:
        - host: "{{ hostname }}"
          serviceName: gateway
          servicePort: 8080
          path: /
        ingressClassName: "{{ ingressClassName }}"
    release_namespace: openfaas
    create_namespace: true
    wait: True
    timeout: 600s
    kubeconfig: "{{ inventory_hostname }}-kubeconfig"
  delegate_to: localhost