version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  resnet50:
    lang: python3-http-debian
    handler: ./resnet50
    image: nightmare224/faas-workload-model-decomposition:resnet50
    secrets:
      - s3-credentials
    annotations:
      com.openfaas.ready.http.path: /model-readiness
      # com.openfaas.retry.attempts: "5"
      # com.openfaas.retry.codes: "429"
      # com.openfaas.retry.min_wait: "5s"
      # com.openfaas.retry.max_wait: "1m"
    #   workload-type: "model-decomposition"
    environment:
      read_timeout: 600
      write_timeout: 600
      exec_timeout: 0
      # max_inflight: 4 # the number set at waitress
      # model name
      model_name: "resnet50-v1-12"
      s3_bucket_name: "faas-workload-model-decomposition"
      s3_object_name: "resnet50-v1-12.onnx"
    # labels:
      # com.openfaas.scale.type: rps
      # com.openfaas.scale.target: 50
      # openfaas.scale.target-proportion: 0.90 
