---
# only master
- name: Ensure the infra directory exists
  file:
    path: /home/{{ ansible_user }}/infra
    state: directory
    mode: '0755'

- name: Ensure the app directory exists
  file:
    path: /home/{{ ansible_user }}/app
    state: directory
    mode: '0755'


- name: Enable cgroup memory of respberrypi
  block:
  - name: Check if the file exists
    stat:
      path: /boot/firmware/cmdline.txt
    register: file_status
  - name: Check if the file exists
    stat:
      path: /boot/firmware/cmdline.txt
    register: file_status
  - name: Add cgroup flags
    lineinfile:
      path: /boot/firmware/cmdline.txt
      regexp: '^(.*)(?<!cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1)$'  # Match lines that do not end with the word
      # line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'  # Append the word at the end of the line
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      backrefs: yes
    register: cgroup_flag
    when: file_status.stat.exists
  - name: Reboot if change
    ansible.builtin.reboot:
      reboot_timeout: 600
    when: cgroup_flag.changed and file_status
  become: yes