
- name: Install wireguard
  apt:
    name: wireguard
  become: yes

- name: Enable ip forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
  become: yes

- name: Generate keypair
  shell: wg genkey | tee wireguard-privateKey | wg pubkey > wireguard-publicKey
  args:
    creates: /home/{{ ansible_user }}/infra/wireguard-privateKey
    chdir: /home/{{ ansible_user }}/infra/

- name: Obtain wireguard private and public key
  block:
  - name: Create directory with wireguard ip
    file:
      path: "{{ role_path }}/files/{{ wireguard_ip }}"
      state: directory
    delegate_to: localhost
  - name: Fetch private and public key
    fetch:
      src: /home/{{ ansible_user }}/infra/wireguard-{{ item }}
      dest: "{{ role_path }}/files/{{ wireguard_ip }}/{{ item }}"
      flat: true
    loop:
      - publicKey
      - privateKey

- name: Obtain wireguard public endpoint
  copy:
    content: "{{ ansible_host }}"
    dest: "{{ role_path }}/files/{{ wireguard_ip }}/endpoint"
  delegate_to: localhost
  when: "'k3s_master' in group_names"

- name: Create wg0.conf for master node
  block:
  - name: transfer add-nat.sh and del-nat.sh
    copy:
      src: "{{ role_path }}/files/{{ item }}"
      dest: /etc/wireguard/{{ item }}
      mode: '0755'
    loop:
      - add-nat.sh
      - del-nat.sh
    become: yes
  - name: Find ip directory
    find:
      paths: "{{ role_path }}/files"
      file_type: directory
      excludes: '10.202.0.1'
    register: ip_dirpath
    delegate_to: localhost
  - name: generate peer id list
    shell: |
      output=""
      for i in $(ls {{ role_path }}/files/ | grep 10); do
        publicKey=$(cat {{ role_path }}/files/${i}/publicKey)
        output="${output}, {\"ip\": \"${i}\", \"publicKey\": \"${publicKey}\"}"
      done
      echo ${output} | sed 's/^, //;s/.*/[&]/'
    register: peers
    delegate_to: localhost
  - name: Set peers 
    set_fact:
      peers: "{{ peers.stdout | from_json }}"
  - name: create wg0.conf for master node
    template:
      src: wg0.master.conf
      dest: /etc/wireguard/wg0.conf
    vars:
      privateKey: "{{ lookup('file', '{{ role_path }}/files/{{ wireguard_ip }}/privateKey') }}"
      peers: "{{ peers }}"
    become: yes
  when: "'k3s_master' in group_names"
  

- name: Create wg0.conf for worker node
  template:
    src: wg0.worker.conf
    dest: /etc/wireguard/wg0.conf
  vars:
    privateKey: "{{ lookup('file', '{{ role_path }}/files/{{ wireguard_ip }}/privateKey') }}"
    peer:
      publicKey: "{{ lookup('file', '{{ role_path }}/files/10.202.0.1/publicKey') }}"
      endpoint: "{{ lookup('file', '{{ role_path }}/files/10.202.0.1/endpoint') }}"
  become: yes
  when: "'k3s_worker' in group_names or 'experiment' in group_names"


- name: start wireguard
  command: wg-quick up wg0
  become: yes
