- block:
  - name: Obtain OpenFaaS client password
    slurp:
      src: "{{ role_path }}/../faasd/files/basic-auth-password/{{ ansible_host }}"
    register: slurped_password
    delegate_to: localhost
  - name: Login faas-cli
    command: faas-cli login --gateway http://{{ ansible_host }}:{{ faasgateway_port }} --password {{ slurped_password.content | b64decode }}
    delegate_to: localhost


- name: Deploy openfaas application
  command: faas-cli deploy --gateway http://{{ ansible_host }}:{{ faasgateway_port }} -f {{ role_path }}/files/workload/stack.yaml # --filter {{ appName }}
  delegate_to: localhost