# - name: Publish openfaas function
#   command: faas-cli publish -f {{ role_path }}/files/workload/stack.yaml --platforms linux/arm64,linux/amd64 # --filter {{ appName }}
#   delegate_to: localhost

- name: Deploy openfaas function
  command: faas-cli deploy --gateway http://{{ ansible_host }}:{{ faasgateway_port }} -f {{ role_path }}/files/workload/stack.yaml
  delegate_to: localhost