---
- name: print ansible_architecture
  debug:
    msg: "{{ ansible_architecture }}"

- name: Copy the install script
  copy:
    src: get.k3s.io.sh
    dest: /tmp/get.k3s.io.sh
    mode: '0755'


- name: Copy K3S master config file
  template:
    src: config-server.yaml
    dest: /home/{{ ansible_user }}/infra/config-server.yaml
  become: yes
  when: "'k3s_master' in group_names"    

- name: Install K3s master
  shell: INSTALL_K3S_EXEC="--config=/home/{{ ansible_user }}/infra/config-server.yaml" /tmp/get.k3s.io.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  args:
    executable: sh
  timeout: 60
  become: yes
  when: "'k3s_master' in group_names" 

- name: Fetch the token of K3S master
  fetch:
    src: /var/lib/rancher/k3s/server/token
    dest: "{{ role_path }}/files/token_{{ group_names[0] }}"
    flat: true
  become: yes
  when: "'k3s_master' in group_names"

- name: Fetch the hostname of K3S master
  ansible.builtin.lineinfile:
    path: "{{ role_path }}/files/hostname_{{ group_names[0] }}"
    line: "{{ ansible_host }}"
    create: true
  delegate_to: localhost
  when: "'k3s_master' in group_names"

- name: Install K3s worker
  shell: /tmp/get.k3s.io.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_TOKEN: "{{ lookup('file', 'token_' + group_names[0]) }}"
    K3S_URL: "https://{{ lookup('file', 'hostname_' + group_names[0]) }}:6443"
  args:
    executable: sh
  become: yes
  when: "'k3s_worker' in group_names"