{{- $namespaceExists := (lookup "v1" "Namespace" "" .Values.functionNamespace) }}
{{- if not $namespaceExists }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.functionNamespace }}
{{- end }}