{{- if .Values.p2p.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: p2p-pubkey
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
{{ (.Files.Glob "p2p/pubKey-peer/*").AsSecrets | indent 2 }}
{{- end }}