{{- if .Values.p2p.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: p2p-privkey
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,post-delete,pre-upgrade,post-rollback"
type: Opaque
data:
  privKey: {{ (.Files.Get (printf "p2p/privKey/%s" .Values.p2p.ip) | b64enc | quote) | indent 2 }}
{{- end }}