{{- if .Values.offload.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: gateway
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install,post-delete,pre-upgrade,post-rollback"
type: Opaque
data:
{{ (.Files.Glob "kubeconfig/*").AsSecrets | indent 2 }}
{{- end }}