{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}
{{- if .Values.prometheus.create }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: prometheus
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.prometheus.serviceType }}
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      {{- if contains "NodePort" .Values.prometheus.serviceType }}
      nodePort: {{ .Values.prometheus.nodePort }}
      {{- end }}
  selector:
    app: prometheus
{{- end }}