{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}

{{- if .Values.prometheus.create }}
{{- if eq .Values.openfaasPro false }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: prometheus-config
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: prometheus-config
  namespace: {{ .Release.Namespace | quote }}
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'faas-monitor'

    rule_files:
        - 'alert.rules.yml'

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus-node-exporter'
        scrape_interval: 10s
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - {{ .Release.Namespace }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: keep
            regex: prometheus-node-exporter

      - job_name: 'prometheus'
        scrape_interval: 10s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'openfaas-pods'
        scrape_interval: 5s
        honor_labels: false
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - {{ .Release.Namespace }}
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__

  alert.rules.yml: |
    groups:
      - name: openfaas
        rules:
        - alert: SlowRequest
          expr: (sum by (function_name) (increase(gateway_functions_seconds_sum{code="200"}[30s]) / increase(gateway_functions_seconds_count{code="200"}[30s])) / sum by (function_name) (gateway_function_fastest_response)) > 8
          for: 20s
          labels:
            service: gateway
            serverity: major
            receiver: scale
        - alert: IdleService
          expr: (sum by (function_name) (increase(gateway_functions_seconds_count{code="200"}[30s]) == 0)) + (sum by (function_name) (gateway_service_count) > 1)
          for: 20s
          labels:
            service: gateway
            serverity: major
            receiver: scale
        # - alert: IdleService
        #   expr: ((sum by (function_name) (increase(gateway_functions_seconds_sum{code="200"}[30s]) / increase(gateway_functions_seconds_count{code="200"}[30s])) / sum by (function_name) (gateway_function_fastest_response)) < 2) + (sum by (function_name) (gateway_service_count) > 1)
        #   for: 20s
        #   labels:
        #     service: gateway
        #     serverity: major
        #     receiver: scale

{{- end }}
{{- end }}