- name: Include common playbook for general setup
  ansible.builtin.import_playbook: common.yaml

- name: Include network topology playbook for all
  ansible.builtin.import_playbook: topology.yaml

- name: Setup Wireguard
  hosts: all
  tasks:
    - name: Check if wiregurad is set
      command: ip a show dev wg0
      failed_when: false
      ignore_errors: true
      register: wg_install
    - name: Run wireguard role
      include_role:
        name: wireguard
      when: "wg_install.rc != 0"

# k3s playbook should also be execute
- name: Include k3s playbook to deploy on cloud and edge side
  ansible.builtin.import_playbook: k3s.yaml
  vars:
    architecture: "centralized"

- name: Include openfaas playbook to deploy on cloud and edge side
  ansible.builtin.import_playbook: openfaas.yaml
  vars:
    architecture: "centralized"