- name: Include common role for general setup
  hosts: database, cloud
  roles:
    - role: common

- name: Include network topology playbook for all
  ansible.builtin.import_playbook: topology.yaml

- name: Setup Wireguard
  hosts: database, cloud
  tasks:
    - name: Check if wiregurad is set
      command: ip a show dev wg0
      failed_when: false
      ignore_errors: true
      register: wg_install
    - name: Bring wireguard down
      command: wg-quick down wg0
      become: yes
      when: "wg_install.rc == 0"  
    - name: Run wireguard role
      include_role:
        name: wireguard

- name: Install minio
  hosts: database
  tasks:
  - name: Download minio
    ansible.builtin.get_url:
      url: https://dl.min.io/server/minio/release/linux-arm64/minio
      dest: /home/{{ ansible_host }}/app/minio
      mode: '0775'
  - name: Run minio
    shell: MINIO_ROOT_USER={{ MINIO_ROOT_USER }} MINIO_ROOT_PASSWORD={{ MINIO_ROOT_PASSWORD }} ./minio server /mnt/data --console-address ":9001" &
    args:
      chdir: /home/{{ ansible_user }}/app/
    become: yes