---
- name: Generate inventory file in json format
  hosts: localhost
  tasks:
    - name: register json format
      command: ansible-inventory -i {{ ansible_inventory_sources[0] }} --list
      register: inventory_content
    - name: output file
      copy:
        content: "{{ inventory_content.stdout }}"
        dest: /tmp/inventory.json


- name: Emulate network toplology
  hosts: all
  tasks:
    - name: Install require tool
      apt:
        name: jq
      become: yes
    - name: Upload inventory file
      copy: 
        src: /tmp/inventory.json
        dest: /tmp/inventory.json
    - name: Execute emulate script
      script: 
        cmd: "{{ playbook_dir }}/../../experiment/net_emulator.sh /tmp/inventory.json {{ ansible_host }} {{ group_names[1] }}"
        chdir: /tmp/
      become: yes

- name: Pull down all image before testing
  hosts: all
  tasks:
    - command: ctr image pull {{ item }}  
      loop:
        - docker.io/nightmare224/matrix-multiplication:latest
        - docker.io/nightmare224/floating-point-operation-sine:latest
        - docker.io/nightmare224/sorter:latest
  become: yes

- name: Install faas-cli
  hosts: localhost
  tasks:
    - name: Check exist
      command: faas-cli version
      register: faas_cli
      failed_when: false
    - name: Install faas_cli
      shell: curl -sSL https://cli.openfaas.com | sudo sh
      when: "faas_cli.rc != 0"

- name: Login openfaas
  hosts: master
  tasks:
    - name: Obtain OpenFaaS client password
      slurp:
        src: "{{ playbook_dir }}/roles/faas_common/files/basic-auth-password/{{ ansible_host }}"
      register: slurped_password
      delegate_to: localhost
    - name: Login faas-cli
      command: faas-cli login --gateway http://{{ ansible_host }}:{{ faasgateway_port }} --password {{ slurped_password.content | b64decode }}
      delegate_to: localhost

- name: Include workload playbook
  ansible.builtin.import_playbook: workload.yaml

- name: Remove openfaas function on edge
  hosts: edge:&master
  tasks:
    - name: Remove openfaas function on edge
      command: faas-cli remove --gateway http://{{ ansible_host }}:{{ faasgateway_port }} -f ./roles/workload/files/workload/stack.yaml
      delegate_to: localhost



# - name: Trigger experiment
#   hosts: localhost
#   tasks:
#     - command: trigger.sh
    
#   vars:
#     user_max: 10
