---
- name: Pull down all image before testing
  hosts: all
  tasks:
    - command: ctr image pull {{ item }}  
      loop:
        # - docker.io/nightmare224/floating-point-operation-sine:latest
        - docker.io/nightmare224/resize-image:latest
  become: yes

- name: Install faas-cli
  hosts: localhost
  tasks:
    - name: Check exist
      command: faas-cli version
      register: faas_cli
      failed_when: false
    - name: Install faas_cli
      shell: curl -sSL https://cli.openfaas.com | sudo sh
      when: "faas_cli.rc != 0"

- name: Login openfaas
  hosts: master
  tasks:
    - name: Obtain OpenFaaS client password
      slurp:
        src: "{{ playbook_dir }}/roles/faas_common/files/basic-auth-password/{{ ansible_host }}"
      register: slurped_password
      delegate_to: localhost
    - name: Login faas-cli
      command: faas-cli login --gateway http://{{ ansible_host }}:{{ faasgateway_port }} --password {{ slurped_password.content | b64decode }}
      delegate_to: localhost

- name: Remove all openfaas function
  hosts: all:&master
  tasks:
    - name: Remove openfaas function on edge
      command: faas-cli remove --gateway http://{{ ansible_host }}:{{ faasgateway_port }} -f ./roles/workload/files/workload/stack.yaml
      delegate_to: localhost
    - name: Wait for delete
      ansible.builtin.pause:
        seconds: 10

- name: Include workload playbook
  ansible.builtin.import_playbook: workload.yaml

