---
- name: Cleanup localhost
  hosts: localhost
  tasks:
    - name: Cleanup faasclient directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/faasclient"
        state: absent
    - name: Cleanup faasclient directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/faasclient"
        state: absent
    - name: Recreate faasclient directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/faasclient"
        state: directory
    - name: Cleanup basic-auth-password directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/basic-auth-password"
        state: absent
    - name: Recreate basic-auth-password directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/basic-auth-password"
        state: directory
    - name: Cleanup p2p directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/p2p"
        state: absent
    - name: Recreate p2p/pubKey-peer directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/p2p/pubKey-peer"
        state: directory
    - name: Recreate p2p/privKey directory
      file:
        path: "{{ playbook_dir }}/roles/faasd/files/p2p/privKey"
        state: directory

- name: Copy required configs to the faasd directory
  hosts: master #on_premise:&master 
  tasks:
    - name: Copy p2p public key
      copy:
        src: "{{ playbook_dir }}/roles/p2p_common/files/p2p/pubKey/{{ ansible_host }}"
        dest: "{{ playbook_dir }}/roles/faasd/files/p2p/pubKey-peer/{{ ansible_host }}"
      delegate_to: localhost
    - name: Copy p2p private key
      copy:
        src: "{{ playbook_dir }}/roles/p2p_common/files/p2p/privKey/{{ ansible_host }}"
        dest: "{{ playbook_dir }}/roles/faasd/files/p2p/privKey/{{ ansible_host }}"
      delegate_to: localhost   
    - name: Copy basic authentication password
      copy:
        src: "{{ playbook_dir }}/roles/faas_common/files/basic-auth-password/{{ ansible_host }}"
        dest: "{{ playbook_dir }}/roles/faasd/files/basic-auth-password/{{ ansible_host }}"
      delegate_to: localhost    

- name: Scatter p2p public key to all faasd node
  hosts: faasd
  tasks:
    - copy:
        src: "{{ playbook_dir }}/roles/faasd/files/p2p/pubKey-peer/"
        dest: /opt/p2p/pubKey-peer/
  become: yes


- name: Setup basic authentication for faasd
  hosts: faasd
  tasks:
    - name: Generate the basic-auth-user
      lineinfile:
        path: /var/lib/faasd/secrets/basic-auth-user
        line: "{{ faasclient_user }}"
        create: true
    - name: Generate the basic-auth-password
      lineinfile:
        path: /var/lib/faasd/secrets/basic-auth-password
        line: "{{ faasclient_password }}"
        regexp: '.*'
        create: true
  vars:
    faasclient_password: "{{ lookup('file', '{{ playbook_dir }}/roles/faas_common/files/basic-auth-password/{{ ansible_host }}') }}"
    faasclient_user: admin
  become: yes

- name: Create faasd client config for all nodes
  hosts: master
  tasks:
    - template: 
        src: "{{ playbook_dir }}/roles/faasd/templates/faasclient.json"
        dest: "{{ playbook_dir }}/roles/faasd/files/faasclient/{{ ansible_host }}"
        mode: 0644
      delegate_to: localhost
  vars:
    faasclient_password: "{{ lookup('file', '{{ playbook_dir }}/roles/faas_common/files/basic-auth-password/{{ ansible_host }}') }}"
    faasclient_user: admin

- name: Scatter faasd client config to all faasd node
  hosts: faasd
  tasks:
    - copy:
        src: "{{ playbook_dir }}/roles/faasd/files/faasclient/"
        dest: /opt/faasd/secrets/faasclient/
  become: yes

- name: Install faasd
  hosts: faasd
  roles:
    - role: faasd
      become: yes