- name: Remove all openfaas function
  hosts: 
    - all:&master
  gather_facts: no
  tasks:
    - name: Remove openfaas function on edge
      command: faas-cli remove --gateway http://{{ ansible_host }}:{{ faasgateway_port }} -f ./roles/workload/files/workload/stack.yaml
      delegate_to: localhost
    - name: Wait for delete
      ansible.builtin.pause:
        seconds: 50

- name: Stop faasd
  hosts: master:&faasd
  gather_facts: no
  tasks:
  - name: Stop faasd-provider
    systemd_service:
      name: faasd-provider
      state: stopped
  - name: Stop faasd
    systemd_service:
      name: faasd
      state: stopped
  - name: Pause for 5 seconds to stop service
    ansible.builtin.pause:
      seconds: 5
  - name: Remove unknown faasd process
    shell: ps aux | grep faasd | awk '{print $2}' | xargs kill -9 2>/dev/null
    ignore_errors: true
    failed_when: false
  become: yes