---
- name: Cleanup localhost
  hosts: localhost
  tasks:
    - name: Cleanup k3s hostname directory 
      file:
        path: "{{ playbook_dir }}/roles/k3s/files/hostname"
        state: absent
    - name: Cleanup k3s token directory 
      file:
        path: "{{ playbook_dir }}/roles/k3s/files/token"
        state: absent
    - name: Recreate k3s hostname directory 
      file:
        path: "{{ playbook_dir }}/roles/k3s/files/hostname"
        state: directory
    - name: Recreate k3s token directory 
      file:
        path: "{{ playbook_dir }}/roles/k3s/files/token"
        state: directory
    # - name: Wireguard ip offset
    #   copy:
    #     content: "2"
    #     dest: "{{ playbook_dir }}/roles/k3s/files/wireguard_ip"

- name: Install K3S
  hosts: all
  roles:
    - k3s