- name: Uninstall openfaas
  hosts: master:&openfaas 
  tasks:
  - name: helm uninstall
    shell: helm uninstall -n openfaas openfaas
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    delegate_to: localhost
  vars:
    kubeconfig: "{{ playbook_dir }}/roles/openfaas/files/openfaas/kubeconfig/{{ group_names[1] }}-kubeconfig"
