---
- name: P2P Common setup
  hosts: 
    - cloud
    - edge
  roles:
    - p2p_common

- name: Common setup
  hosts: master #on_premise:&master
  roles:
    - common

- name: Fetch the kubeconfig file from all Kubernetes server
  hosts: master #on_premise:&master
  tasks:
    - name: From the on-premsie cluster
      fetch:
        src: "{{ kubeconfig_path }}"
        # dest: "{{ playbook_dir }}/roles/openfaas/files/openfaas/kubeconfig/{{ inventory_hostname }}-kubeconfig"
        dest: "{{ playbook_dir }}/roles/openfaas/files/openfaas/kubeconfig/{{ inventory_hostname }}-kubeconfig"
        flat: true
      # when: 
      #   "('on_premise' in group_names) and ('master' in group_names)"

# need login before hand
# - name: Fetch the kubeconfig file from all Kubernetes server
#   hosts: aks
#   vars:
#     ansible_python_interpreter: /opt/homebrew/Caskroom/miniforge/base/envs/faas-workload/bin/python3
#   tasks:
#     - block:
#       - name: From AKS
#         azure_rm_aks_info:
#           # ad_user: "{{ aks_ad_user }}"
#           # password: "{{ aks_password }}"
#           subscription_id: "{{ aks_subscription_id }}"
#           name: "{{ aks_name }}"
#           resource_group: "{{ aks_resource_group }}"
#           show_kubeconfig: admin
#         register: resp_kubeconfig
#       - name: Save kubeconfig
#         copy:
#           content: "{{ resp_kubeconfig['aks'][0]['kube_config'] }}"
#           # dest: "{{ playbook_dir }}/roles/openfaas/files/openfaas/kubeconfig/{{ inventory_hostname }}-kubeconfig"
#           dest: "{{ playbook_dir }}/roles/openfaas/files/{{ inventory_hostname }}-kubeconfig"
#       # when: "'aks' in group_names"
    


- name: Copy required configs to the Helm chart
  hosts: master #on_premise:&master 
  tasks: 
    - name: Copy p2p public key
      copy:
        src: "{{ playbook_dir }}/roles/p2p_common/files/p2p/pubKey/{{ ansible_host }}"
        dest: "{{ playbook_dir }}/roles/openfaas/files/openfaas/p2p/pubKey-peer/{{ ansible_host }}"
      delegate_to: localhost
    - name: Copy p2p private key
      copy:
        src: "{{ playbook_dir }}/roles/p2p_common/files/p2p/privKey/{{ ansible_host }}"
        dest: "{{ playbook_dir }}/roles/openfaas/files/openfaas/p2p/privKey/{{ ansible_host }}"
      delegate_to: localhost

- name: Install OpenFaaS on Kubernetes
  hosts: master
    # - on_premise:&master
    # - aks
  gather_facts: no
  roles:
    - openfaas
  tags: openfaas_helm_update