---
- name: Create symbolic link
  hosts: localhost
  tasks:
    - name: Create workload
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../experiment/workload"
        dest: "{{ playbook_dir }}/roles/workload/files/workload"
        state: link

- name: Deploy openfaas workload
  hosts: cloud:&master
  roles:
    - role: workload