---
- name: Create symbolic link
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create file
      file:
        path: "{{ playbook_dir }}/roles/workload/files/"
        state: directory
    - name: Create workload
      ansible.builtin.file:
        src: "{{ playbook_dir }}/../../experiment/workload"
        dest: "{{ playbook_dir }}/roles/workload/files/workload"
        state: link

- name: Deploy openfaas workload
  hosts: 
    - cloud:&master
    # - peerA-1
    # - peerA-2
    # - peerB-1
    # - peerB-2
  gather_facts: no
  roles:
    - role: workload